# Generated by Django 2.2.4 on 2020-01-17 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Userinfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='group',
        ),
    ]
