# Generated by Django 2.2.4 on 2020-01-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userinfo', '0002_remove_userinfo_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='is_superadmin',
            field=models.CharField(default=1, max_length=10, verbose_name='是否是超级管理员'),
            preserve_default=False,
        ),
    ]
