# Generated by Django 2.2.4 on 2020-01-17 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Userinfo', '0003_userinfo_is_superadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupuser',
            name='group_name',
            field=models.CharField(max_length=10, verbose_name='角色管理'),
        ),
        migrations.AlterUniqueTogether(
            name='groupuser',
            unique_together={('group_name',)},
        ),
        migrations.CreateModel(
            name='ClientUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=10, verbose_name='用户名称')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Userinfo.Groupuser')),
            ],
            options={
                'verbose_name': '客户模块角色表',
                'verbose_name_plural': '客户模块角色表',
                'db_table': 'user_celinet',
                'unique_together': {('client_name',)},
            },
        ),
    ]
