# Generated by Django 2.2.4 on 2020-01-17 14:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Userinfo', '0004_auto_20200117_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='SFunMsgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_code', models.CharField(max_length=10, verbose_name='菜单栏的code')),
                ('menu_name', models.CharField(max_length=30, verbose_name='菜单栏名称')),
                ('url', models.CharField(max_length=30, verbose_name='url路径')),
                ('menu_level', models.CharField(max_length=5, verbose_name='菜单栏的级别')),
                ('father_code', models.CharField(max_length=10, verbose_name='父级菜单栏id')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('creat_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '导航栏表',
                'verbose_name_plural': '导航栏表',
                'db_table': 'user_sfunmsgs',
                'unique_together': {('menu_code', 'menu_name', 'url', 'menu_level', 'father_code')},
            },
        ),
    ]
