# Generated by Django 2.2.4 on 2020-01-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userinfo', '0005_sfunmsgs'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100, verbose_name='订单号')),
                ('data_times', models.CharField(max_length=100, verbose_name='订单时间')),
                ('consignor', models.CharField(max_length=30, verbose_name='发货人')),
                ('consignor_phone', models.CharField(max_length=30, verbose_name='发货人电话')),
            ],
        ),
        migrations.AddField(
            model_name='clientuser',
            name='address',
            field=models.CharField(default=1, max_length=30, verbose_name='地址'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientuser',
            name='phone',
            field=models.CharField(default=1, max_length=30, verbose_name='电话'),
            preserve_default=False,
        ),
    ]
