# Generated by Django 2.2.4 on 2020-01-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userinfo', '0006_auto_20200117_2315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theorder',
            options={'verbose_name': '订单模块', 'verbose_name_plural': '订单模块'},
        ),
        migrations.RenameField(
            model_name='theorder',
            old_name='consignor',
            new_name='post_user',
        ),
        migrations.RenameField(
            model_name='theorder',
            old_name='consignor_phone',
            new_name='post_user_phone',
        ),
        migrations.AddField(
            model_name='theorder',
            name='com_name',
            field=models.CharField(default=1, max_length=30, verbose_name='货物名称'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theorder',
            name='com_number',
            field=models.CharField(default=1, max_length=30, verbose_name='货物数量'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theorder',
            name='com_weight',
            field=models.CharField(default=1, max_length=30, verbose_name='货物重量'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theorder',
            name='freight',
            field=models.CharField(default=1, max_length=30, verbose_name='运费'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theorder',
            name='get_user',
            field=models.CharField(default=1, max_length=30, verbose_name='收货人'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theorder',
            name='get_user_address',
            field=models.CharField(default=1, max_length=30, verbose_name='收货人地址'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theorder',
            name='get_user_phone',
            field=models.CharField(default=1, max_length=30, verbose_name='收货人电话'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theorder',
            name='goods_note',
            field=models.CharField(default=1, max_length=30, verbose_name='货物备注'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theorder',
            name='note',
            field=models.CharField(default=1, max_length=30, verbose_name='订单备注'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theorder',
            name='post_user_address',
            field=models.CharField(default=1, max_length=30, verbose_name='发货人地址'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theorder',
            name='rebates',
            field=models.CharField(default=1, max_length=30, verbose_name='返款'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theorder',
            name='single_price',
            field=models.CharField(default=1, max_length=30, verbose_name='单件'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theorder',
            name='status',
            field=models.CharField(default=1, max_length=30, verbose_name='订单状态'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theorder',
            name='take_way',
            field=models.CharField(default=11, max_length=30, verbose_name='取件方式'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theorder',
            name='term_payment',
            field=models.CharField(default=1, max_length=30, verbose_name='付款方式'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='theorder',
            unique_together={('order_number', 'data_times')},
        ),
        migrations.AlterModelTable(
            name='theorder',
            table='the_order',
        ),
    ]
