# Generated by Django 2.2.4 on 2020-01-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userinfo', '0008_auto_20200117_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='TLogCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provinces', models.CharField(max_length=30, verbose_name='省份')),
                ('city', models.CharField(max_length=30, verbose_name='城市')),
                ('county', models.CharField(max_length=30, verbose_name='县')),
                ('tounsty', models.CharField(max_length=30, verbose_name='乡')),
                ('money', models.CharField(max_length=30, verbose_name='费用')),
            ],
            options={
                'verbose_name': '物流费用模块',
                'verbose_name_plural': '物流费用模块',
                'db_table': 'tlog',
                'unique_together': {('provinces', 'city', 'county', 'tounsty')},
            },
        ),
    ]
