# Generated by Django 2.2.4 on 2020-01-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userinfo', '0011_theorder_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='theorder',
            name='com_name1',
            field=models.CharField(default=1, max_length=30, verbose_name='货物名称'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theorder',
            name='com_name2',
            field=models.CharField(default=1, max_length=30, verbose_name='货物名称'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theorder',
            name='com_number1',
            field=models.CharField(default=1, max_length=30, verbose_name='货物数量'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theorder',
            name='com_number2',
            field=models.CharField(default=1, max_length=30, verbose_name='货物数量'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theorder',
            name='com_weight1',
            field=models.CharField(default=1, max_length=30, verbose_name='货物重量'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theorder',
            name='com_weight2',
            field=models.CharField(default=1, max_length=30, verbose_name='货物重量'),
            preserve_default=False,
        ),
    ]
