# Generated by Django 2.2.4 on 2020-01-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userinfo', '0013_auto_20200120_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='theorder',
            name='all_freight',
            field=models.CharField(default=1, max_length=30, verbose_name='总运费'),
            preserve_default=False,
        ),
    ]
